### ISSUE TITLE
ChiBot has passed Turing test

### ISSUE THREAD

**Issue by skyzh** [YoruCathy/Chi-Bot#6]
Mr. Du has made a ChiBot that passed Turing test. The group administrator can not tell Alex Chi from ChiBot in trial test today. From my perspective, this is a great leap of artificial intelligence. This can be added into the readme. 

https://github.com/dujiajun/ChiBot

**Comment by trackoor** [comment]
Agree!

**Comment by YoruCathy** [comment]
It has been added to Chi-task-force's repo.
